export interface CountryOption {
  name: string
  code: string
  flag: string
  region: string
}

export const countriesList: CountryOption[] = [
  { name: "Afghanistan", code: "AF", flag: "AF", region: "Asia" },
  { name: "Albania", code: "AL", flag: "AL", region: "Europe" },
  { name: "Algeria", code: "DZ", flag: "DZ", region: "Africa" },
  { name: "Andorra", code: "AD", flag: "AD", region: "Europe" },
  { name: "Angola", code: "AO", flag: "AO", region: "Africa" },
  { name: "Antigua and Barbuda", code: "AG", flag: "AG", region: "North America" },
  { name: "Argentina", code: "AR", flag: "AR", region: "South America" },
  { name: "Armenia", code: "AM", flag: "AM", region: "Asia" },
  { name: "Australia", code: "AU", flag: "AU", region: "Oceania" },
  { name: "Austria", code: "AT", flag: "AT", region: "Europe" },
  { name: "Azerbaijan", code: "AZ", flag: "AZ", region: "Asia" },
  { name: "Bahamas", code: "BS", flag: "BS", region: "North America" },
  { name: "Bahrain", code: "BH", flag: "BH", region: "Asia" },
  { name: "Bangladesh", code: "BD", flag: "BD", region: "Asia" },
  { name: "Barbados", code: "BB", flag: "BB", region: "North America" },
  { name: "Belarus", code: "BY", flag: "BY", region: "Europe" },
  { name: "Belgium", code: "BE", flag: "BE", region: "Europe" },
  { name: "Belize", code: "BZ", flag: "BZ", region: "North America" },
  { name: "Benin", code: "BJ", flag: "BJ", region: "Africa" },
  { name: "Bhutan", code: "BT", flag: "BT", region: "Asia" },
  { name: "Bolivia", code: "BO", flag: "BO", region: "South America" },
  { name: "Bosnia and Herzegovina", code: "BA", flag: "BA", region: "Europe" },
  { name: "Botswana", code: "BW", flag: "BW", region: "Africa" },
  { name: "Brazil", code: "BR", flag: "BR", region: "South America" },
  { name: "Brunei", code: "BN", flag: "BN", region: "Asia" },
  { name: "Bulgaria", code: "BG", flag: "BG", region: "Europe" },
  { name: "Burkina Faso", code: "BF", flag: "BF", region: "Africa" },
  { name: "Burundi", code: "BI", flag: "BI", region: "Africa" },
  { name: "Cambodia", code: "KH", flag: "KH", region: "Asia" },
  { name: "Cameroon", code: "CM", flag: "CM", region: "Africa" },
  { name: "Canada", code: "CA", flag: "CA", region: "North America" },
  { name: "Cape Verde", code: "CV", flag: "CV", region: "Africa" },
  { name: "Central African Republic", code: "CF", flag: "CF", region: "Africa" },
  { name: "Chad", code: "TD", flag: "TD", region: "Africa" },
  { name: "Chile", code: "CL", flag: "CL", region: "South America" },
  { name: "China", code: "CN", flag: "CN", region: "Asia" },
  { name: "Colombia", code: "CO", flag: "CO", region: "South America" },
  { name: "Comoros", code: "KM", flag: "KM", region: "Africa" },
  { name: "Congo", code: "CG", flag: "CG", region: "Africa" },
  { name: "Costa Rica", code: "CR", flag: "CR", region: "North America" },
  { name: "Croatia", code: "HR", flag: "HR", region: "Europe" },
  { name: "Cuba", code: "CU", flag: "CU", region: "North America" },
  { name: "Cyprus", code: "CY", flag: "CY", region: "Europe" },
  { name: "Czech Republic", code: "CZ", flag: "CZ", region: "Europe" },
  { name: "Democratic Republic of the Congo", code: "CD", flag: "CD", region: "Africa" },
  { name: "Denmark", code: "DK", flag: "DK", region: "Europe" },
  { name: "Djibouti", code: "DJ", flag: "DJ", region: "Africa" },
  { name: "Dominica", code: "DM", flag: "DM", region: "North America" },
  { name: "Dominican Republic", code: "DO", flag: "DO", region: "North America" },
  { name: "East Timor", code: "TL", flag: "TL", region: "Asia" },
  { name: "Ecuador", code: "EC", flag: "EC", region: "South America" },
  { name: "Egypt", code: "EG", flag: "EG", region: "Africa" },
  { name: "El Salvador", code: "SV", flag: "SV", region: "North America" },
  { name: "Equatorial Guinea", code: "GQ", flag: "GQ", region: "Africa" },
  { name: "Eritrea", code: "ER", flag: "ER", region: "Africa" },
  { name: "Estonia", code: "EE", flag: "EE", region: "Europe" },
  { name: "Eswatini", code: "SZ", flag: "SZ", region: "Africa" },
  { name: "Ethiopia", code: "ET", flag: "ET", region: "Africa" },
  { name: "Fiji", code: "FJ", flag: "FJ", region: "Oceania" },
  { name: "Finland", code: "FI", flag: "FI", region: "Europe" },
  { name: "France", code: "FR", flag: "FR", region: "Europe" },
  { name: "Gabon", code: "GA", flag: "GA", region: "Africa" },
  { name: "Gambia", code: "GM", flag: "GM", region: "Africa" },
  { name: "Georgia", code: "GE", flag: "GE", region: "Asia" },
  { name: "Germany", code: "DE", flag: "DE", region: "Europe" },
  { name: "Ghana", code: "GH", flag: "GH", region: "Africa" },
  { name: "Greece", code: "GR", flag: "GR", region: "Europe" },
  { name: "Grenada", code: "GD", flag: "GD", region: "North America" },
  { name: "Guatemala", code: "GT", flag: "GT", region: "North America" },
  { name: "Guinea", code: "GN", flag: "GN", region: "Africa" },
  { name: "Guinea-Bissau", code: "GW", flag: "GW", region: "Africa" },
  { name: "Guyana", code: "GY", flag: "GY", region: "South America" },
  { name: "Haiti", code: "HT", flag: "HT", region: "North America" },
  { name: "Honduras", code: "HN", flag: "HN", region: "North America" },
  { name: "Hungary", code: "HU", flag: "HU", region: "Europe" },
  { name: "Iceland", code: "IS", flag: "IS", region: "Europe" },
  { name: "India", code: "IN", flag: "IN", region: "Asia" },
  { name: "Indonesia", code: "ID", flag: "ID", region: "Asia" },
  { name: "Iran", code: "IR", flag: "IR", region: "Asia" },
  { name: "Iraq", code: "IQ", flag: "IQ", region: "Asia" },
  { name: "Ireland", code: "IE", flag: "IE", region: "Europe" },
  { name: "Israel", code: "IL", flag: "IL", region: "Asia" },
  { name: "Italy", code: "IT", flag: "IT", region: "Europe" },
  { name: "Ivory Coast", code: "CI", flag: "CI", region: "Africa" },
  { name: "Jamaica", code: "JM", flag: "JM", region: "North America" },
  { name: "Japan", code: "JP", flag: "JP", region: "Asia" },
  { name: "Jordan", code: "JO", flag: "JO", region: "Asia" },
  { name: "Kazakhstan", code: "KZ", flag: "KZ", region: "Asia" },
  { name: "Kenya", code: "KE", flag: "KE", region: "Africa" },
  { name: "Kiribati", code: "KI", flag: "KI", region: "Oceania" },
  { name: "Kuwait", code: "KW", flag: "KW", region: "Asia" },
  { name: "Kyrgyzstan", code: "KG", flag: "KG", region: "Asia" },
  { name: "Laos", code: "LA", flag: "LA", region: "Asia" },
  { name: "Latvia", code: "LV", flag: "LV", region: "Europe" },
  { name: "Lebanon", code: "LB", flag: "LB", region: "Asia" },
  { name: "Lesotho", code: "LS", flag: "LS", region: "Africa" },
  { name: "Liberia", code: "LR", flag: "LR", region: "Africa" },
  { name: "Libya", code: "LY", flag: "LY", region: "Africa" },
  { name: "Liechtenstein", code: "LI", flag: "LI", region: "Europe" },
  { name: "Lithuania", code: "LT", flag: "LT", region: "Europe" },
  { name: "Luxembourg", code: "LU", flag: "LU", region: "Europe" },
  { name: "Madagascar", code: "MG", flag: "MG", region: "Africa" },
  { name: "Malawi", code: "MW", flag: "MW", region: "Africa" },
  { name: "Malaysia", code: "MY", flag: "MY", region: "Asia" },
  { name: "Maldives", code: "MV", flag: "MV", region: "Asia" },
  { name: "Mali", code: "ML", flag: "ML", region: "Africa" },
  { name: "Malta", code: "MT", flag: "MT", region: "Europe" },
  { name: "Marshall Islands", code: "MH", flag: "MH", region: "Oceania" },
  { name: "Mauritania", code: "MR", flag: "MR", region: "Africa" },
  { name: "Mauritius", code: "MU", flag: "MU", region: "Africa" },
  { name: "Mexico", code: "MX", flag: "MX", region: "North America" },
  { name: "Micronesia", code: "FM", flag: "FM", region: "Oceania" },
  { name: "Moldova", code: "MD", flag: "MD", region: "Europe" },
  { name: "Monaco", code: "MC", flag: "MC", region: "Europe" },
  { name: "Mongolia", code: "MN", flag: "MN", region: "Asia" },
  { name: "Montenegro", code: "ME", flag: "ME", region: "Europe" },
  { name: "Morocco", code: "MA", flag: "MA", region: "Africa" },
  { name: "Mozambique", code: "MZ", flag: "MZ", region: "Africa" },
  { name: "Myanmar", code: "MM", flag: "MM", region: "Asia" },
  { name: "Namibia", code: "NA", flag: "NA", region: "Africa" },
  { name: "Nauru", code: "NR", flag: "NR", region: "Oceania" },
  { name: "Nepal", code: "NP", flag: "NP", region: "Asia" },
  { name: "Netherlands", code: "NL", flag: "NL", region: "Europe" },
  { name: "New Zealand", code: "NZ", flag: "NZ", region: "Oceania" },
  { name: "Nicaragua", code: "NI", flag: "NI", region: "North America" },
  { name: "Niger", code: "NE", flag: "NE", region: "Africa" },
  { name: "Nigeria", code: "NG", flag: "NG", region: "Africa" },
  { name: "North Korea", code: "KP", flag: "KP", region: "Asia" },
  { name: "North Macedonia", code: "MK", flag: "MK", region: "Europe" },
  { name: "Norway", code: "NO", flag: "NO", region: "Europe" },
  { name: "Oman", code: "OM", flag: "OM", region: "Asia" },
  { name: "Pakistan", code: "PK", flag: "PK", region: "Asia" },
  { name: "Palau", code: "PW", flag: "PW", region: "Oceania" },
  { name: "Panama", code: "PA", flag: "PA", region: "North America" },
  { name: "Papua New Guinea", code: "PG", flag: "PG", region: "Oceania" },
  { name: "Paraguay", code: "PY", flag: "PY", region: "South America" },
  { name: "Peru", code: "PE", flag: "PE", region: "South America" },
  { name: "Philippines", code: "PH", flag: "PH", region: "Asia" },
  { name: "Poland", code: "PL", flag: "PL", region: "Europe" },
  { name: "Portugal", code: "PT", flag: "PT", region: "Europe" },
  { name: "Qatar", code: "QA", flag: "QA", region: "Asia" },
  { name: "Romania", code: "RO", flag: "RO", region: "Europe" },
  { name: "Russia", code: "RU", flag: "RU", region: "Europe" },
  { name: "Rwanda", code: "RW", flag: "RW", region: "Africa" },
  { name: "Saint Kitts and Nevis", code: "KN", flag: "KN", region: "North America" },
  { name: "Saint Lucia", code: "LC", flag: "LC", region: "North America" },
  { name: "Saint Vincent and the Grenadines", code: "VC", flag: "VC", region: "North America" },
  { name: "Samoa", code: "WS", flag: "WS", region: "Oceania" },
  { name: "San Marino", code: "SM", flag: "SM", region: "Europe" },
  { name: "Sao Tome and Principe", code: "ST", flag: "ST", region: "Africa" },
  { name: "Saudi Arabia", code: "SA", flag: "SA", region: "Asia" },
  { name: "Senegal", code: "SN", flag: "SN", region: "Africa" },
  { name: "Serbia", code: "RS", flag: "RS", region: "Europe" },
  { name: "Seychelles", code: "SC", flag: "SC", region: "Africa" },
  { name: "Sierra Leone", code: "SL", flag: "SL", region: "Africa" },
  { name: "Singapore", code: "SG", flag: "SG", region: "Asia" },
  { name: "Slovakia", code: "SK", flag: "SK", region: "Europe" },
  { name: "Slovenia", code: "SI", flag: "SI", region: "Europe" },
  { name: "Solomon Islands", code: "SB", flag: "SB", region: "Oceania" },
  { name: "Somalia", code: "SO", flag: "SO", region: "Africa" },
  { name: "South Africa", code: "ZA", flag: "ZA", region: "Africa" },
  { name: "South Korea", code: "KR", flag: "KR", region: "Asia" },
  { name: "South Sudan", code: "SS", flag: "SS", region: "Africa" },
  { name: "Spain", code: "ES", flag: "ES", region: "Europe" },
  { name: "Sri Lanka", code: "LK", flag: "LK", region: "Asia" },
  { name: "Sudan", code: "SD", flag: "SD", region: "Africa" },
  { name: "Suriname", code: "SR", flag: "SR", region: "South America" },
  { name: "Sweden", code: "SE", flag: "SE", region: "Europe" },
  { name: "Switzerland", code: "CH", flag: "CH", region: "Europe" },
  { name: "Syria", code: "SY", flag: "SY", region: "Asia" },
  { name: "Taiwan", code: "TW", flag: "TW", region: "Asia" },
  { name: "Tajikistan", code: "TJ", flag: "TJ", region: "Asia" },
  { name: "Tanzania", code: "TZ", flag: "TZ", region: "Africa" },
  { name: "Thailand", code: "TH", flag: "TH", region: "Asia" },
  { name: "Togo", code: "TG", flag: "TG", region: "Africa" },
  { name: "Tonga", code: "TO", flag: "TO", region: "Oceania" },
  { name: "Trinidad and Tobago", code: "TT", flag: "TT", region: "North America" },
  { name: "Tunisia", code: "TN", flag: "TN", region: "Africa" },
  { name: "Turkey", code: "TR", flag: "TR", region: "Asia" },
  { name: "Turkmenistan", code: "TM", flag: "TM", region: "Asia" },
  { name: "Tuvalu", code: "TV", flag: "TV", region: "Oceania" },
  { name: "Uganda", code: "UG", flag: "UG", region: "Africa" },
  { name: "Ukraine", code: "UA", flag: "UA", region: "Europe" },
  { name: "United Arab Emirates", code: "AE", flag: "AE", region: "Asia" },
  { name: "United Kingdom", code: "GB", flag: "GB", region: "Europe" },
  { name: "United States", code: "US", flag: "US", region: "North America" },
  { name: "Uruguay", code: "UY", flag: "UY", region: "South America" },
  { name: "Uzbekistan", code: "UZ", flag: "UZ", region: "Asia" },
  { name: "Vanuatu", code: "VU", flag: "VU", region: "Oceania" },
  { name: "Vatican City", code: "VA", flag: "VA", region: "Europe" },
  { name: "Venezuela", code: "VE", flag: "VE", region: "South America" },
  { name: "Vietnam", code: "VN", flag: "VN", region: "Asia" },
  { name: "Yemen", code: "YE", flag: "YE", region: "Asia" },
  { name: "Zambia", code: "ZM", flag: "ZM", region: "Africa" },
  { name: "Zimbabwe", code: "ZW", flag: "ZW", region: "Africa" }
]

export function searchCountries(query: string): CountryOption[] {
  const searchTerm = query.toLowerCase().trim()
  if (!searchTerm) return []
  
  return countriesList.filter(country => 
    country.name.toLowerCase().includes(searchTerm) ||
    country.code.toLowerCase().includes(searchTerm)
  ).slice(0, 10) // Limit to 10 results
} 